
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<table> 
   <tr>
    <th>Name</th>
    <th>Image path</th>
    <th>ID</th>
    </tr>

    <?php
    $ids = [1,2,3];
    $categoryProducts = $block->getProductCollectionByCategories($ids);
    foreach ($categoryProducts as $product) {
        echo '<tr>
            <td>'. $product->getName().' </td>
            <td>'.$product->getImage().' </td>
            <td> '.$product->getId().'</td>;
            </tr>';
    }
    ?>
    
 </table>

</body>
</html>